# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - hotwok

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://hotwok.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_2f77f7d0740a40448d07bc8c676274d6 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1c041ca3b8754e378cab5308438e2cb8 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: hotwok.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2f77f7d0740a40448d07bc8c676274d6 }}/resturantsite:${{ github.sha }}
        file: ./Dockerfile.prod

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'hotwok'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9112bdd972f1424b90a1585a4eb70c2e }}
        images: 'hotwok.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2f77f7d0740a40448d07bc8c676274d6 }}/resturantsite:${{ github.sha }}'
